### ISSUE TITLE
dotzu eat my parameters？

### ISSUE THREAD

**Issue by dars** [remirobert/Dotzu#10]
hello..
when i use dotzu and alamofire together
i wrote a small project, when i click button, send a request to api
first time click it's work nice, but when i click second times my parameters is gone...
![2017-02-20 4 47 16](https://cloud.githubusercontent.com/assets/192553/23117798/57df96f2-f78c-11e6-8882-c24236363844.png)
but when i remove `Dotzu.sharedManager.displayWindow()` it's work great
is there something wrong with my code？

**Comment by remirobert** [comment]
Fixed, thanks for reporting the issue, and making Dotzu better.
You can update the framework, version 1.5.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@dars
