### ISSUE TITLE
 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Manager' in bundle NSBundle

### ISSUE THREAD

**Issue by thedoubler** [remirobert/Dotzu#11]
Nice library and work, but cannot use it. Am I missing something? 
Added using CocoaPods.

Thanks,

**Comment by remirobert** [comment]
Can you check the pod version of the framework you are using please ?
You can find it in your **Podfile.lock**.

**Comment by thedoubler** [comment]
The version is - Dotzu (0.1)
Please tell me that you need any info

**Comment by remirobert** [comment]
update your **Podfile** with that, and you are ready to go !!

```ruby
pod 'Dotzu', '~> 1.5'
```

Or you can try a ```pod update```.
But be sure to use the last version : **1.5**

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@thedoubler
