### ISSUE TITLE
Network - don't scroll to bottom after popping detail view

### ISSUE THREAD

**Issue by natalia-osa** [remirobert/Dotzu#15]
Let's say I've got 10000 network requests recorded in the Network tab. I want to investigate top 10 (the oldest ones). I need to scroll all the way up (by the way - tap on the status bar to scroll to the top doesn't work), select a cell, read everything in the details view. Then I tap `back` and it takes me to the list, but it scrolls all the way down to the newest records, and I have to scroll all the way up once again, same for the next request etc.

**Comment by remirobert** [comment]
Yes sorry about that, when the view appear, I scroll the list down. I made that by design. I will check to improve that.

Thanks for reporting that.

**Comment by remirobert** [comment]
Fix it's the version 1.7.
you can update by doing a ```pod update```

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@natalia-osa
