### ISSUE TITLE
Make please support ios 8.0

### ISSUE THREAD

**Issue by tigrim** [remirobert/Dotzu#16]
Now, I have same problem with storyboard and other parts of project.

**Comment by remirobert** [comment]
Hello @tigrim can you be more specific about the issues you got ?
Can you upload some screenshots if it's relevant to your issue ? 🐸

**Comment by tigrim** [comment]
i am use project without **pods**. If my developer target less 9.0, i have next error: **storyboard reference cannot be the destination of relationship segues prior to iOS 9.0** (Manager.storyboard)

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@tigrim
