### ISSUE TITLE
Crash sessions don't capture all null dereferences on device

### ISSUE THREAD

**Issue by DanielAsher** [remirobert/Dotzu#17]
Hi,

thanks for an incredible project - a real tour de force.

I have noticed that certain crashes in my application are not caught by Dotzu when run on device. Replacing [this](https://github.com/remirobert/Dotzu/blob/master/Example/Example/CrashTestTableViewController.swift#L18) line with:
```
    private func crashSigbart() {
        let a : Int? = nil
        _ = a!  
   }
```
produces no crash report on restart.

Would someone be able to verify this?

many thanks,

Daniel

**Comment by remirobert** [comment]
Thanks for reporting that. I will have a look. 👀

**Comment by DanielAsher** [comment]
I googled around and found `SIGTRAP` being used in [this](https://github.com/plausiblelabs/plcrashreporter/blob/05d34741d3a90bbed51214983110943831ae5943/Source/PLCrashReporter.m#L88) line to trap null dereferences on device. More info [here](http://stackoverflow.com/questions/10315526/exc-bad-access-automatic-handling). 

I implemented on my fork [here](https://github.com/DanielAsher/Dotzu/commit/ae20009ea1cd15028be70232ce0decd330930d59#diff-f113af2ad44cec4a35b415cf5964f6faL57) and tested on device. It works!

Let me know if you'd like a PR.
![dotzu crash session sigtrap](https://cloud.githubusercontent.com/assets/7915553/23822684/bad4540c-0649-11e7-8f08-64ac620a907b.PNG)

**Comment by remirobert** [comment]
@DanielAsher Thanks for your research. I would love a PR. 🍻

**Comment by DanielAsher** [comment]
see #19

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@DanielAsher
