### ISSUE TITLE
Consider allowing show / hide window functionality

### ISSUE THREAD

**Issue by DanielAsher** [remirobert/Dotzu#18]
Hi again,

I require show / hide window functionality to use with the excellent [SwiftTweaks](https://github.com/Khan/SwiftTweaks) project. This allows a more advanced TestFlight user to monitor and understand the app. I have a trivial implementation [here](https://github.com/DanielAsher/Dotzu/commit/228664747f68ae987a8a95f409d38d026d1176c9#diff-6311f567bb444164053726a3d9e63589R37) but would be very pleased to discuss a PR if you were open to it.

thanks again and have a wonderful day!

Daniel

**Comment by remirobert** [comment]
The feature to hide/show the dotzu window, was already asked. I will add it in priority.

**Comment by remirobert** [comment]
done version 1.8

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@DanielAsher
