### ISSUE TITLE
Allow public function to disable console logging.

### ISSUE THREAD

**Issue by DanielAsher** [remirobert/Dotzu#20]
I'm using XCGLogger in conjunction with Dotzu (#6) and have disabled default console logging to avoid duplicates [here.](https://github.com/DanielAsher/Dotzu/blob/danielasher/develop/Dotzu/Logger.swift#L56)

A better solution would be to allow a public function to configure this. Would you like a PR?

thanks,
Daniel

**Comment by DanielAsher** [comment]
that'll be all this morning 😅. thanks for your attention 🏋️.

**Comment by remirobert** [comment]
I am working on it. That will be a major update for the project.

**Comment by wwe-johndpope** [comment]
Another noteworthy contender for logging - https://github.com/emaloney/CleanroomLogger/issues/50

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@DanielAsher
