### ISSUE TITLE
Enhancements  - Logger + nserror  + tap to expand

### ISSUE THREAD

**Issue by wwe-johndpope** [remirobert/Dotzu#21]
currently - I am passing this 
 Logger.error(error?.localizedDescription)

but swift 3 wants me to pass something like this
  Logger.error(error?.localizedDescription ?? "")

I think escalating the nserrors into the logger is the number 1 value proposition for testers to see.
so any kind of help here to simplify for users of control I think would go a long way.

perhaps the error could be overloaded with an nserror helper.
open to ideas.

One thing that I will mention - in this project
https://github.com/PTEz/LumberjackConsole

you could Tap on a item and it would expand the object into more details. 
You should take a look - definitely would go a long way - there's also a nifty control to filter by 
verbose / Debug / etc that works well + as well a text search. 
I feel like Santa when I was a kid wishing for gifts..... but if you don't ask.....

also I actually prefer the https://github.com/zixun/GodEye in app  icon - it's black. it sits better with the designs I'm working with /its more hidden. 
the lumberjack console was also less obtrusive. maybe you could have a toggle rocket config switch.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@wwe-johndpope
