### ISSUE TITLE
defect - when I switch to errors I'm still seeing counter increment.

### ISSUE THREAD

**Issue by wwe-johndpope** [remirobert/Dotzu#24]
<img width="380" alt="screen shot 2017-03-28 at 3 50 06 pm" src="https://cloud.githubusercontent.com/assets/26149651/24424338/43626192-13ce-11e7-8470-9e01cd3f8551.png">

I wonder if it would make most sense if inner circle could be used as a kind of reg / orange /blue / grey... just an idea.
![docs_190726c_pie_chart_en](https://cloud.githubusercontent.com/assets/26149651/24424418/7eaac528-13ce-11e7-877b-1d904c693f36.gif)

I think the design would sit with apps better if the dark grey background opacity is weak / almost transparent 30%. that way it's hidden from app.   (awesome job on this btw)

**Comment by remirobert** [comment]
like stats for the logs for example ? or request status ?
I really need new icon, design, and mockups.

**Comment by wwe-johndpope** [comment]
I wonder whether it would be best to provide a delegate method
then people could switch in there own uiview and respond with animations / tricks.

**Comment by remirobert** [comment]
I am working on a modular version, where anyone can create module for Dotzu. Then with protocol Logger, you can log or display what you want. And even create custom Cells.

But it takes time ⌚️.

**Comment by wwe-johndpope** [comment]
Remi, do share the alpha branch - I can take a look.

**Comment by remirobert** [comment]
sureI will make a branch. I planned to start working on it next week. I will let you know here.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@wwe-johndpope
