### ISSUE TITLE
Only print statements from 1st view controller appear in dotzu log

### ISSUE THREAD

**Issue by Mozahler** [remirobert/Dotzu#31]
I have a tab bar controller with each view controller inside a navigation controller getting its own tab. In Xcode I get log messages that don't appear in the app (dotzu's green and black screen). It seems I only get messages from the 1st view controller, but not the 2nd.  Do I need to enable in each file, or just in the AppDelegate.swift file? What else could I be doing wrong?

**Comment by wwe-johndpope** [comment]
paste the code in a gist.
did you set a break point? maybe the print logging is not being invoked.
try with print ("Test")

**Comment by Mozahler** [comment]
why would it be invoked in one view controller and not the other? the only "code" is:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        Dotzu.sharedManager.enable()
....
}
```

**Comment by johndpope** [comment]
what logging are you using? 

Logger.verbose("Test")

Do you have some settings switched off in app screen to disable some conditions?

**Comment by remirobert** [comment]
very strange, as @johndpope which Logger are you using. 
Even if you are using print, you will need to **import Dotzu** everywhere.

**Comment by Mozahler** [comment]
Thanks. The readme instructions said to put it in app delegate. I guess they should say but it in any class you want to trace.

**Comment by remirobert** [comment]
So you can initialise **Dotzu** everywhere in your app.
Dotzu will analyse everything by default.
If you want only a specific class, you will need to **enabled** and **disabled** Dotzu.

**Comment by remirobert** [comment]
@Mozahler  Here what you can do : 

```swift
//When you enter in the controller
Dotzu.sharedManager.enable()

//When you leave the controller
Dotzu.sharedManager.disable()
```

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@Mozahler @wwe-johndpope @johndpope
