### ISSUE TITLE
crash on background thread

### ISSUE THREAD

**Issue by johndpope** [remirobert/Dotzu#32]
<img width="1430" alt="screen shot 2017-05-19 at 12 51 33 pm" src="https://cloud.githubusercontent.com/assets/289994/26258278/fa5b1f2e-3c91-11e7-8eda-567eb6d92212.png">

I updated a PINCache sample gist here
https://gist.github.com/johndpope/1dd3663a8712bb1901536a44bccd6a5a

**Comment by johndpope** [comment]
It seems to be reproducible  in my code base under obscure edge case in background thread.
code below is woven across different classes. In any case - this is the fragility of nsarchiver / threading. 
  


```swift
let kFixStatusButtonColorOnCloseButtonPress = NSNotification.Name("kFixStatusButtonColorOnCloseButtonPress")

// Class that is being torn down.
// ClassA.VC
   override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        Notificator.fireNotification(named: kFixStatusButtonColorOnCloseButtonPress)
    }


// ClassB.VC
    func addObserverForStatusBarFixOnFilterClose(){
        NotificationCenter.default.addObserver(self, selector: #selector(resyncStatusBarColor), name: kFixStatusButtonColorOnCloseButtonPress, object: nil)
    }
    
    override func resyncStatusBarColor(){
//        Logger.verbose("resyncStatusBarColor") <- BOOM
     
    }
```

**Comment by johndpope** [comment]
this is unrelated to my bug.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@johndpope
