### ISSUE TITLE
enhancement - fps overlay

### ISSUE THREAD

**Issue by johndpope** [remirobert/Dotzu#36]
https://github.com/sagesse-cn/swift-chat

![img_9402](https://user-images.githubusercontent.com/289994/27483940-66c29f7e-57f5-11e7-8f2b-5b9d5429f90c.PNG)

**Comment by johndpope** [comment]
closing this
the code is here if you're interested
https://github.com/sagesse-cn/swift-chat/blob/fc2146552e70d3dad7bebfaba4fbb47a44404ee8/Librarys/FPSLabel.swift

**Comment by remirobert** [comment]
Thanks @johndpope . I almost finished the version 2.
I am also trying to have a test coverage close to 100% to allows contributions.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@johndpope
