### ISSUE TITLE
Dotzu + Alamofire

### ISSUE THREAD

**Issue by MaxCavalheiro** [remirobert/Dotzu#38]
Hello, 

I'm using Alamofire to handler my requests, and in your tutorial  you mentions it:
**/Your custom configuration
let configuration = URLSessionConfiguration.default

///Add the network logger on the configuration
Dotzu.sharedManager.addLogger(session: configuration)

//Use it:
//For Alamofire
let sessionManager = Alamofire.SessionManager(configuration: configuration)

//For URLSession
let session = URLSession(configuration: configuration)**

But I didn't use session in my requests, I make it directly ex:
**Alamofire.request(url, method: .put, parameters..............**  
And it not log request on Doutzu, I think that it is because of session, How can I set a session in Alamofire manager??

Thx

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@MaxCavalheiro

**Comment by liman123** [comment]
[DebugMan](https://github.com/liman123/DebugMan) is forked form Dotzu.
It support any HTTP requests with just one line codes in AppDelegate.swift `DebugMan.shared.enable()`
This is more convenient. @MaxCavalheiro

**Comment by mohamadrezakoohkan** [comment]
you should create a session manager and use session manager instead of alamofire directly, dotzu need to observer the session configuration that you set.
