### ISSUE TITLE
Some text in "application" and "settings" page is not shown.

### ISSUE THREAD

**Issue by jkyeo** [remirobert/Dotzu#4]
It looks like below:
![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-08-WX20170208-100102.png)
![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-08-WX20170208-100055.png)

**Comment by remirobert** [comment]
Awwwww that's weird. The **TextColor** is setted to white, directly on the storyboard.
Is it an accessibility issue somehow ?

**Comment by jkyeo** [comment]
@remirobert Yes, testing it on iPhone SE and iPhone 7 simulator (iOS 10.2), the issue appeared every time.

**Comment by remirobert** [comment]
@jkyeo ok, how did you integrate **Dotzu** cocoapods, carthage, code ?

**Comment by jkyeo** [comment]
@remirobert via cocoapods.

**Comment by remirobert** [comment]
@jkyeo it's extremely strange it works fine one my devices, and simulator. 
Do you have any clue for this issue ?

**Comment by jkyeo** [comment]
@remirobert
No more at the present moment.
I will test it on my device later.

**Comment by jkyeo** [comment]
@remirobert Same issue on my device (iPhone 6s Plus running iOS 10.2.1).

**Comment by jkyeo** [comment]
Running view debug. It shows the text color is black.
![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-08-WX20170208-152037.png)

**Comment by remirobert** [comment]
Can you check on the storyboard directly ? **Pods/Dotzy/Resources/Settings.storyboard**

**Comment by jkyeo** [comment]
@remirobert No problem!
![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-08-WX20170208-160724.png)

**Comment by remirobert** [comment]
I am lost... 😢

**Comment by jkyeo** [comment]
Strange issue...

**Comment by remirobert** [comment]
Stranger things...
Try to reinstall the Pod ? Be sure you have the last one 0.6.
I will close it for now. if it persists, or if you find the solution let me know.
Thanks for reported it.

**Comment by jkyeo** [comment]
I'm sorry this is my fault.
I set `UILabel.appearance().textColor = defaultTextColor` in some place.
Remove it. fixed.

**Comment by remirobert** [comment]
no problem. 👍🏼

**Comment by TaiPhamD** [comment]
![img_0002](https://user-images.githubusercontent.com/10516699/27519751-7423d9ce-59af-11e7-90cb-7b02e42adcb0.PNG)
![img_0001](https://user-images.githubusercontent.com/10516699/27519752-74242df2-59af-11e7-825e-f58ebe6d06e4.PNG)


I am having issues with text color and I dont see where in my code i could override it. any tips?

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@jkyeo
