### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by hernangonzalez** [remirobert/Dotzu#45]
Hello @remirobert,

Will you continue support to swift-4? Cocoapods version does not compile at the moment.

Thanks,
H.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@hernangonzalez

**Comment by liman123** [comment]
[DebugMan](https://github.com/liman123/DebugMan) is forked form Dotzu.
It support Swift-4. @hernangonzalez

**Comment by hernangonzalez** [comment]
Good to know, thanks.
