### ISSUE TITLE
Network logging doesn't seem to work

### ISSUE THREAD

**Issue by edasque** [remirobert/Dotzu#5]
Even though it's enabled in the settings, after doing a few network requests (based on Alamofire), nothing seems to register in the network tab.

Erik

**Comment by remirobert** [comment]
Ok, did you had the logger to your **Alamofire manager** ?

```swift
let configuration = URLSessionConfiguration.default

//This line add the logger to your configuration
Dotzu.sharedManager.addLogger(session: configuration)

sessionManager = Alamofire.SessionManager(configuration: configuration)

sessionManager.request(url).responseJSON { response in
        Logger.info("response for url : [\(url)] : \(response)")
}
```

**Comment by remirobert** [comment]
@edasque did it work for you ?
Please reopen the request if not.

Thanks. 🙏

**Comment by edasque** [comment]
I must be missing out something obvious because by adding this code, none of my queries succeed, most of them with a canceled (500?) some just silently in gray with a request latency of 0ms. I don't really know what to do from here. I changed:
```
    let configuration = URLSessionConfiguration.default
        
    Alamofire.request(API_URL, method:.get, parameters: search_parameters).responseJSON { response in

```
to
```
    let configuration = URLSessionConfiguration.default
        
    // This line add the logger to your configuration
    Dotzu.sharedManager.addLogger(session: configuration)
    
    let alamofireSessionManager = Alamofire.SessionManager(configuration: configuration)
    let start = Date()
    alamofireSessionManager.request(API_URL, method:.get, parameters: search_parameters).responseJSON { response in
```

**Comment by edasque** [comment]
@remirobert , FYI I can't re-open

**Comment by edasque** [comment]
OK, je laisse tomber. @remirobert . Not worth waiting that long, switching to https://github.com/zixun/GodEye

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@edasque
