### ISSUE TITLE
ObjC support?

### ISSUE THREAD

**Issue by nickbit** [remirobert/Dotzu#7]
Hello,

this seems a very good debugging tool. Any plans to support ObjC?

**Comment by remirobert** [comment]
Currently, I have an issue with the ```Logger``` class.
The implementation is not compatible with Objc.
I planned to add a new class for Objc support, and maybe override the NSLog.

But the rest is compatible, you can use the network and crash debugger.

**Comment by nickbit** [comment]
Thank you for the quick response. 
Can you provide an ObjC example project that shows how to add Dotzu?

**Comment by remirobert** [comment]
https://github.com/remirobert/Dotzu-Objective-c

You can find an example project. Working fully in Objective-c, with AFNetworking.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@nickbit
