### ISSUE TITLE
minimum deployment target

### ISSUE THREAD

**Issue by dars** [remirobert/Dotzu#8]
hello, can you support minimum deployment target iOS 9.0？
i use carthage to install Dotzu
when i use on my project when i build
i got alert message Module files minimum deployment target is iOS 10.2 v10.2...

**Comment by remirobert** [comment]
Fixed with version 0.9
minimum target reported to iOS 9.

**Comment by dars** [comment]
thank you.. ：）

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@dars
