### ISSUE TITLE
Dotzu affect preferredStatusBarStyle in UIViewController

### ISSUE THREAD

**Issue by jkyeo** [remirobert/Dotzu#9]
I override preferredStatusBarStyle as .lightContent in my viewController:
> ```swift
> override var preferredStatusBarStyle: UIStatusBarStyle {
>     return .lightContent
>  }
> ```
Without Dotzu injected, everything is ok. But when I use Dotzu, the statusBar style shown as .default.
![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-17-WechatIMG1.jpeg) ![](http://7xqi9q.com1.z0.glb.clouddn.com/2017-02-17-WechatIMG2.jpeg)

**Comment by remirobert** [comment]
I guess it's normal, because Dotzu has its own window, with its own root view controller.
I would say, if it's working without Dotzu, it's fine (it will be in the production app).
If you want to have the same status bar you need to do the modification in the Dotzu framework as well.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@jkyeo
